name: Lint Check

on:
  pull_request:
    types: [synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: black Lint
        uses: psf/black@stable
        args: ['--config=pyproject.toml', '-v']
      - name: flake8 Lint
        uses: py-actions/flake8@v2
